# Generated by Django 4.2.11 on 2024-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_ticket_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='archived_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job_category',
            field=models.IntegerField(choices=[(0, 'Plumbing'), (1, 'Electrical'), (2, 'Heating'), (3, 'Cleaning'), (4, 'Vending Services'), (5, 'Air Conditioning'), (6, 'Waste'), (7, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
