# Generated by Django 4.2.11 on 2024-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_is_complete_ticket_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
